name: Build, Save, Upload and Run Docker Image
on:
  push:
    branches:
      - '**' # Run on all branches

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build \
          -f Dockerfile \
          -t toy-example-image \
          --platform linux/amd64 \
          .
      working-directory: ${{ github.workspace }}

    - name: Save Docker image
      run: |
        mkdir -p docker-image
        docker save toy-example-image:latest | gzip > docker-image/toy-example-image.tar.gz

    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v2
      with:
        name: toy-example-image
        path: docker-image/toy-example-image.tar.gz

    - name: Run Docker container
      run: |
        docker run \
          --rm \
          --name toy-example-container \
          toy-example-image

